version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  mock-openshopping:
    image: wiremock/wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./mocks:/home/wiremock
    command: --global-response-templating --verbose

volumes:
  redis_data: